# -*- coding: utf-8 -*-
"""resnet152 (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i2bJsXEkQkELu3c4p1mw7omjjS5n2RK3
"""

import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from torchvision import transforms
from torch.utils.data import Dataset, DataLoader
from sklearn.preprocessing import LabelEncoder
import torch.optim as optim

df = pd.read_csv('/kaggle/input/ham10000-isic2018-raw/dataverse_files/HAM10000_metadata')

import os
kaggle_image_dir = '/kaggle/input/ham10000-isic2018-raw/dataverse_files/HAM10000_images_combined_600x450'
complete_paths = []
for col in df['image_id']:
    col += '.jpg'
    complete_paths.append(os.path.join(kaggle_image_dir, col))
df['full_path'] = complete_paths
df.head(5)

le = LabelEncoder()
df['labels'] = le.fit_transform(df['dx'])

X, y = df['full_path'], df['labels']

X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size = 0.3, random_state = 42)

X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size = 0.5, random_state = 42)

from PIL import Image

custom_transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor()
    ])

class CustomDataset(Dataset):

    def __init__(self, features, labels, transform):
        self.features = features
        self.labels = labels
        self.transform = transform

    def __len__(self):
        return len(self.features)

    def __getitem__(self, index):
        img = Image.open(self.features.iloc[index]).convert("RGB")
        img = self.transform(img)
        return img, torch.tensor(self.labels.iloc[index], dtype = torch.long)

train_dataset = CustomDataset(X_train, y_train, custom_transform)
val_dataset = CustomDataset(X_val, y_val, custom_transform)
test_dataset = CustomDataset(X_test, y_test, custom_transform)

train_loader = DataLoader(train_dataset, batch_size = 32, shuffle = True, pin_memory = True)
val_loader = DataLoader(val_dataset, batch_size = 32, shuffle = False, pin_memory = True)
test_loader = DataLoader(test_dataset, batch_size = 32, shuffle = False, pin_memory = True)

class resnet_block(nn.Module):
    def __init__(self, in_channels, out_channels, identity_downsample = None, stride = 1):
        super().__init__()
        self.conv1 = nn.Conv2d(in_channels, out_channels, kernel_size = 1, stride = 1, padding = 0)
        self.bn1 = nn.BatchNorm2d(out_channels)
        self.conv2 = nn.Conv2d(out_channels, out_channels, kernel_size = 3, stride = stride, padding = 1) # padding 1 in 3x3 preserves spatial dimension
        self.bn2 = nn.BatchNorm2d(out_channels)
        self.conv3 = nn.Conv2d(out_channels, out_channels*4, kernel_size = 1, stride = 1, padding = 0)
        self.bn3 = nn.BatchNorm2d(out_channels*4)
        self.relu = nn.ReLU()
        self.identity_downsample = identity_downsample

    def forward(self, x):
        identity = x

        x = self.conv1(x)
        x = self.bn1(x)
        x = self.relu(x)
        x = self.conv2(x)
        x = self.bn2(x)
        x = self.relu(x)
        x = self.conv3(x)
        x = self.bn3(x)

        if self.identity_downsample is not None:
            identity = self.identity_downsample(identity)

        x += identity
        x = self.relu(x)
        return x


class ResNet(nn.Module):
    def __init__(self, block, resnet_layers, image_channels, num_classes):
        super().__init__()
        self.in_channels = 64
        self.conv1 = nn.Conv2d(image_channels, 64, kernel_size = 7, stride = 2, padding = 3)
        self.bn1 = nn.BatchNorm2d(64)
        self.relu = nn.ReLU()
        self.maxpool = nn.MaxPool2d(kernel_size = 3, stride = 2, padding = 1)

        # ResNet layers
        self.layer1 = self._make_layer(block, resnet_layers[0], 64, 1)
        self.layer2 = self._make_layer(block, resnet_layers[1], 128, 2)
        self.layer3 = self._make_layer(block, resnet_layers[2], 256, 2)
        self.layer4 = self._make_layer(block, resnet_layers[3], 512, 2)

        self.fc = nn.Linear(2048, num_classes)
        self.avgpool = nn.AdaptiveAvgPool2d((1, 1))

    def _make_layer(self, block, num_residual_blocks, out_channels, stride):
        identity_downsample = None
        layers = []

        if stride != 1 or self.in_channels != out_channels * 4:
            identity_downsample = nn.Sequential(nn.Conv2d(self.in_channels, out_channels*4, kernel_size = 1, stride = stride),
                                               nn.BatchNorm2d(out_channels * 4))

        layers.append(block(self.in_channels, out_channels, identity_downsample, stride))
        self.in_channels = out_channels * 4

        for i in range(num_residual_blocks - 1):
            layers.append(block(self.in_channels, out_channels))

        return nn.Sequential(*layers)

    def forward(self, x):
        x = self.conv1(x)
        x = self.bn1(x)
        x = self.relu(x)
        x = self.maxpool(x)
        x = self.layer1(x)
        x = self.layer2(x)
        x = self.layer3(x)
        x = self.layer4(x)
        x = self.avgpool(x)
        x = torch.flatten(x, 1)
        x = self.fc(x)
        return x

resnet152 = ResNet(resnet_block, [3, 8, 36, 3], 3, 7)

optimizer = optim.Adam(resnet152.parameters(), lr = 0.00001, weight_decay = 1e-4)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

resnet152.to(device)

criterion = nn.CrossEntropyLoss()

train_acc = []
val_acc = []
train_loss = []
val_loss = []
for epoch in range(25):
    resnet152.train()
    total = 0
    correct = 0
    total_val = 0
    correct_val = 0
    total_epoch_loss = 0.0
    total_val_loss = 0.0
    for batch_features, batch_labels in train_loader:
        batch_features = batch_features.to(device)
        batch_labels = batch_labels.to(device)
        out = resnet152(batch_features)
        loss = criterion(out, batch_labels)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        _, predicted = torch.max(out, 1)
        correct += (predicted == batch_labels).sum().item()
        total += batch_labels.shape[0]
        total_epoch_loss += loss.item()

    avg_epoch_loss = total_epoch_loss/len(train_loader)
    acc = (correct/total)*100.0
    print(f"Epoch: {epoch+1}")
    print(f"Train Loss: {avg_epoch_loss:.4f}")
    print(f"Train Accuracy: {acc:.2f}%")
    train_acc.append(acc)
    train_loss.append(avg_epoch_loss)

    resnet152.eval()
    with torch.no_grad():
        for batch_features, batch_labels in val_loader:
            batch_features = batch_features.to(device)
            batch_labels = batch_labels.to(device)
            out = resnet152(batch_features)
            loss = criterion(out, batch_labels)
            _, predicted = torch.max(out, 1)
            correct_val += (predicted == batch_labels).sum().item()
            total_val += batch_labels.shape[0]
            total_val_loss += loss.item()
        avg_val_loss = total_val_loss/len(val_loader)
        val_acc_epoch = (correct_val/total_val)*100.0
        print(f"Val Loss: {avg_val_loss:.4f}")
        print(f"Val Accuracy: {val_acc_epoch:.2f}%")
        val_acc.append(val_acc_epoch)
        val_loss.append(avg_val_loss)
    print("---")

resnet152.eval()
test_loss = 0.0
total = 0
correct = 0
with torch.no_grad():
    for batch_features, batch_labels in test_loader:
        batch_features = batch_features.to(device)
        batch_labels = batch_labels.to(device)
        out = resnet152(batch_features)
        loss = criterion(out, batch_labels)
        _, predicted = torch.max(out, 1)
        correct += (predicted == batch_labels).sum().item()
        total += batch_labels.shape[0]
        test_loss += loss.item() * batch_labels.shape[0]
    test_acc = (correct/total)*100
    test_loss /= total
print(f"Test Acc: {test_acc:.2f}")
print(f"Test Loss: {test_loss:.2f}")

import matplotlib.pyplot as plt

epochs = list(range(1, 26))

plt.figure(figsize=(8, 5))
plt.plot(epochs, train_acc, label="Train Accuracy")
plt.plot(epochs, val_acc, label="Validation Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy (%)")
plt.title("ResNet-152: Training vs Validation Accuracy")
plt.legend()

plt.savefig(
    "/kaggle/working/train_val_accuracy_resnet152.png",
    dpi=300,
    bbox_inches="tight"
)
plt.show()
plt.close()

plt.figure(figsize=(8, 5))
plt.plot(epochs, train_loss, label="Train Loss")
plt.plot(epochs, val_loss, label="Validation Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("ResNet-152: Training vs Validation Loss")
plt.legend()

plt.savefig(
    "/kaggle/working/train_val_loss_resnet152.png",
    dpi=300,
    bbox_inches="tight"
)
plt.show()
plt.close()

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Accuracy
axes[0].plot(epochs, train_acc, label="Train Accuracy")
axes[0].plot(epochs, val_acc, label="Validation Accuracy")
axes[0].set_xlabel("Epoch")
axes[0].set_ylabel("Accuracy (%)")
axes[0].set_title("ResNet-152: Training vs Validation Accuracy")
axes[0].legend()

# Loss
axes[1].plot(epochs, train_loss, label="Train Loss")
axes[1].plot(epochs, val_loss, label="Validation Loss")
axes[1].set_xlabel("Epoch")
axes[1].set_ylabel("Loss")
axes[1].set_title("ResNet-152: Training vs Validation Loss")
axes[1].legend()

plt.tight_layout()
plt.savefig(
    "/kaggle/working/train_val_combined_resnet152.png",
    dpi=300,
    bbox_inches="tight"
)
plt.show()
plt.close()

